# Generated by Django 5.0.6 on 2024-05-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_application", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=80),
        ),
    ]
